export const ROOM_NAMESPACE = '/room';
export const ROOM_ERROR_CODES = ['ROOM_NOT_FOUND', 'PASSWORD_REQUIRED', 'INVALID_PASSWORD', 'FORBIDDEN', 'INVALID_PHASE', 'INVALID_VOTE', 'ROOM_FULL', 'AI_UNAVAILABLE', 'INVALID_PROFILE_UPDATE', 'INVALID_ROLE_REQUEST', 'PROFILE_REQUEST_NOT_FOUND', 'REMOVED', 'NOT_PARTICIPANT', 'INVALID_CONFIG'];
//# sourceMappingURL=index.js.map